PKG := wnix

build:
	wnix switch --flake .#wnix

# install?
# mkdir -p /mnt/wnix
## get nixos-install in any distro:
# nix shell nixpkgs#nixos-install-tools -c nixos-install --root /mnt/wnix --system ./result
